language: node_js
cache:
  directories:
    - ~/.npm
    - ~/.cache
install:
  - npm i -g npm@6
  - npm ci
node_js:
  - lts/*
script:
  - npm run test:ci
after_success:
  - git checkout ${TRAVIS_BRANCH}
  - npm run release -- --yes
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
