version: "3"

services:
  wp:
    container_name: frontity_wp
    image: wordpress:5.0
    ports:
      - 8080:80
    volumes:
      - wp_data:/var/www/html
      - ./data/uploads/:/var/www/html/wp-content/uploads
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
    depends_on:
      - db
    links:
      - db

  wpcli:
    container_name: frontity_wpcli
    image: wordpress:cli
    volumes:
      - wp_data:/var/www/html
    depends_on:
      - db
      - wp

  db:
    container_name: frontity_db
    image: mysql:latest
    command:
      [
        "--default_authentication_plugin=mysql_native_password",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
      ]
    volumes:
      - db_data:/var/lib/mysql
      - ./data:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: password

volumes:
  wp_data:
  db_data:
