name: e2e tests

on: [pull_request]

jobs:
  e2e-tests:
    strategy:
      matrix:
        name:
          - Test Chrome
          - Test Firefox
          - Test Edge
          - Test ES5 in Chrome
          - Test ES5 in Firefox
          - Test ES5 in Edge
          - Test previous WordPress version
          - Test custom relative public-path
          - Test custom absolute public-path

        image: ["cypress/browsers:node12.18.0-chrome83-ff77"]
        os: ["ubuntu-16.04"]
        options: ["--user 1000"]

        include:
          - name: Test Chrome
            wp-version: latest
            browser: chrome
            target: both

          - name: Test Firefox
            wp-version: latest
            browser: firefox
            target: both
            options: "--user 1001"

          - name: Test Edge
            wp-version: latest
            browser: edge
            target: both
            os: windows-latest

          - name: Test ES5 in Chrome
            wp-version: latest
            browser: chrome
            target: es5

          - name: Test ES5 in Firefox
            wp-version: latest
            browser: firefox
            target: es5
            options: "--user 1001"

          - name: Test ES5 in Edge
            wp-version: latest
            browser: edge
            target: es5
            os: windows-latest

          - name: Test previous WordPress version
            wp-version: 5.4
            browser: chrome
            target: both

          - name: Test custom relative public-path
            wp-version: latest
            browser: chrome
            target: both
            public-path: /custom/path

          - name: Test custom absolute public-path
            wp-version: latest
            browser: chrome
            target: both
            public-path: http://localhost:3001/custom/path

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup npm cache
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies (root)
        run: npm ci
        env:
          CI: true

      - name: Run e2e tests
        uses: cypress-io/github-action@v2
        env:
          # We need to specify the WordPress version here as well so that
          # it's available inside of the cypress GH action container
          WORDPRESS_VERSION: ${{ matrix.wordpress_version }}
        with:
          start: "node e2e.js \
            --wpVersion ${{ matrix.wordpress_version }} \
            --target ${{ matrix.target }} \
            --prod \
            --cypress off \
            --publicPath ${{ matrix.publicPath }} \
            --suite all"
          headless: true
          wait-on: "http://localhost:3001"
          wait-on-timeout: 600
          browser: ${{ matrix.browser }}
          working-directory: e2e
          config: video=true,screenshotOnRunFailure=true

      - name: Upload screenshots on failure
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: e2e/screenshots

      - name: Upload videos
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: cypress-videos
          path: e2e/videos
