name: firefox e2e tests

on: [pull_request]

jobs:
  e2e-tests:
    runs-on: ubuntu-16.04

    strategy:
      matrix:
        target: [both, es5]

    container:
      image: cypress/browsers:node12.16.1-chrome80-ff73
      options: --user 1001

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup npm cache
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies (root)
        run: npm ci
        env:
          CI: true

      - name: Run e2e tests
        uses: cypress-io/github-action@v2
        env:
          WORDPRESS_VERSION: latest
        with:
          start: "node e2e.js \
            --wpVersion latest \
            --target ${{ matrix.target }} \
            --prod \
            --cypress off \
            --suite all"
          headless: true
          wait-on: "http://localhost:3001"
          wait-on-timeout: 600
          browser: firefox
          working-directory: e2e
          config: video=true,screenshotOnRunFailure=true

      - name: Upload screenshots on failure
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: e2e/screenshots

      - name: Upload videos
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: cypress-videos
          path: e2e/videos
