name: check PR tasks

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  tasks:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/task-completed-checker-action@v0.1.0
        if: ${{ github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository }}
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
