version: "3"

services:
  wp:
    image: wordpress:5.0
    ports:
      - 8080:80
    # The wordpress container will retry to connect to the mysql database for 30 seconds
    # after starting. However, it might take longer than this for mysql container
    # to initialize (inluding loading data into the DB). For this reason, if the
    # wordpress container times out, we have to restart it
    restart: always
    volumes:
      - wp_data:/var/www/html
      - ./data:/var/www/html/wp-content
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
    depends_on:
      - db
    links:
      - db

  wpcli:
    image: wordpress:cli
    volumes:
      # Needs to share a volume with the `wp` service so that the CLI can run the commands
      - wp_data:/var/www/html
    depends_on:
      - db
      - wp

  db:
    image: mysql:latest
    command:
      [
        "--default_authentication_plugin=mysql_native_password",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
      ]
    volumes:
      - db_data:/var/lib/mysql
      # The mysql image will load any .sql file in the ./data folder
      - ./data:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: password

volumes:
  wp_data:
  db_data:
